version: 0.2
phases:
    pre_build:
        commands:
          - npm install
    build:
        commands:
          - npm build
          - npm test
artifacts:
        type: zip
        files:
          - '**/*'
reports:
    calc-reports:
        files:
            - 'report.xml'
        file-format: JunitXml
        base-directory: 'test_reports'
    cov-reports:
        files:
            - 'coberturareport.xml'
        file-format: Coberturaxml
        base-directory: 'cov_reports'    
