version: 0.2

phases:
    pre_build:
        commands:
          - npm install
    build:
        commands:
          - jasmine

reports:
    calculator-reports:
        files:
            - '**/*'
        file-format: JunitXml
        base-directory: 'spec'
