version: 0.2
phases:
    pre_build:
        commands:
          - npm install
    build:
        commands:
          - npm build
          - npm test
artifacts:
    files:
          - '**/*
reports:
    calculator-reports:
        files:
            - 'report.xml'
        file-format: JunitXml
        base-directory: 'test_reports'
